### ISSUE TITLE
Can't load any file

### ISSUE THREAD

**Issue by lvivtotoro** [libgdx/fbx-conv#97] opened 2016-05-26 15:53 UTC
Whenever I try to load an FBX file the program says this:
`-----------------------------------
fbx-conv-win32.exe -v -m 32 -b 12 -w 4  spaceship1.fbx libgdx-model-viewer.temp.g3dj

INFO:     FBX to G3Dx converter, version 0.01.0071 x32 , FBXSDK 2015.01
STATUS:   Loading source file
ERROR:    FBX SDK encountered an error (1): Unexpected file type
ERROR:    Error loading source file
STATUS:   Closing source file
`

If it's an OBJ:
`-----------------------------------
fbx-conv-win32.exe -v -m 32 -b 12 -w 4  spaceship1.obj libgdx-model-viewer.temp.g3dj

INFO:     FBX to G3Dx converter, version 0.01.0071 x32 , FBXSDK 2015.01
STATUS:   Loading source file
ERROR:    FBX SDK encountered an error (1): File not opened
ERROR:    Error loading source file
STATUS:   Closing source file`

**Comment by xoppa** [comment] 2016-05-26 16:44
Works fine for me. Without more information my guess is that your source model is invalid or something.

**Comment by lvivtotoro** [comment] 2016-05-26 16:48
I exported both of them from C4D. Really have no idea what to change in the export settings.

**Comment by xoppa** [comment] 2016-05-26 17:04
How did you verify it is indeed an issue with fbx-conv and not with the file? Perhaps consider testing the file in another application the uses FBX-SDK. E.g. the Autodesk FBX Converter.

**Comment by lvivtotoro** [comment] 2016-05-26 17:27
I just tried Autodesk's FBX converter and it worked.

**Comment by xoppa** [comment] 2016-05-26 18:07
Must be something else then, perhaps try another file or desktop. Anyways, as said, without the required information to reproduce the issue, there's not much we can do.

**Comment by lvivtotoro** [comment] 2016-06-25 06:22
I tried it on my Ubuntu and the same error occoured.

**Comment by xoppa** [comment] 2016-06-25 09:31
Yeah, let's close this. As said, if you don't want to provide the required information then there is nothing we can do.

**Closed by xoppa** 2016-06-25 09:31 UTC

**Comment by JoryRFerrell** [comment] 2016-09-26 01:24
Check the format of the FBX file. Blender for instance exports either FBX 6.1 ASCIIor FBX 7.4 Binary. 
Exporting as FBX 7.4 Binary threw the same error for me, but the ASCII format version works. Maybe support for different formats could be added to FBX-Conv for convenience?

**Comment by CliffBurton** [comment] 2018-04-30 16:05
Got the same issue with C4D R19, since this issue pops in the first page on google I would like to share what worked for me:
inspecting the .obj file exported by C4D it comes out that it has some empty lines, just remove them and repeat the conversion, it works.

**Comment by userLikun** [comment] 2018-12-05 11:36
![image](https://user-images.githubusercontent.com/13050154/49510780-3fa73000-f8c4-11e8-9631-12e3b94368a0.png)
![image](https://user-images.githubusercontent.com/13050154/49510810-5483c380-f8c4-11e8-91ec-61ce152331a1.png)
![image](https://user-images.githubusercontent.com/13050154/49511036-f7d4d880-f8c4-11e8-84f6-fefc5d61c0d8.png)

Got the same issue with 3D demo file
